---
# tasks file for apigee-opdk-backup
- name: Stop component if it is not Postgres
  shell: '{{ apigee_service }} {{ component_profile }} stop'
  when: component_profile != 'apigee-postgresql' or component_profile != 'all'

- name: Start component if it is Postgres
  shell: '{{ apigee_service }} {{ component_profile }} start'
  when: component_profile == 'apigee-postgresql'

- name: Backup component {{ component_profile }}
  shell: '{{ apigee_service }} {{ component_profile }} backup'
  when: component_profile != 'all'

- name: Backup component {{ component_profile }}
  shell: '{{ apigee_all }} backup'
  when: component_profile == 'all'

- name: Start component {{ component_profile }}
  shell: '{{ apigee_service }} {{ component_profile }} start'
  when: component_profile != 'all'
