---
# tasks file for opdk-backup
- name: Stop component
  shell: '{{ apigee_service }} {{ component_profile }} stop'
  when: component_profile != 'apigee-postgresql'

- name: Backup component
  shell: '{{ apigee_service }} {{ component_profile }} backup'

- name: Stop component
  shell: '{{ apigee_service }} {{ component_profile }} start'
