---
# tasks file for apigee-opdk-backup
- name: Stop component {{ component_name }}
  shell: '{{ apigee_service }} {{ component_name }} stop'
  when: component_name != 'apigee-postgresql' and component_name != 'all'

- name: Backup component {{ component_name }}
  shell: '{{ apigee_service }} {{ component_name }} backup'
  when: component_name != 'all'

- name: Backup component {{ component_name }}
  shell: '{{ apigee_all }} backup'
  when: component_name == 'all'

- name: Start component {{ component_name }}
  shell: '{{ apigee_service }} {{ component_name }} start'
  when: component_name != 'apigee-postgresql' and component_name != 'all'
