---
# tasks file for opdk-backup
- name: Stop component
  shell: '{{ apigee_service }} {{ component_profile }} stop'

- name: Backup component
  shell: '{{ apigee_service }} {{ component_profile }} backup'

- name: Stop component
  shell: '{{ apigee_service }} {{ component_profile }} start'
